--- #YAML:1.0
name:                Class-Prototyped-Mixin
version:             3
abstract:            Mixin Support for Class::Prototyped
license:             ~
author:              
    - Terrence Brannon (metaperl@gmail.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Prototyped:             1.11
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
