# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Prototyped-Mixin
version:      2.3
version_from: lib/Class/Prototyped/Mixin.pm
installdirs:  site
requires:
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
